// Generated database types for Supabase
// This will be auto-generated by supabase gen types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: 'operations' | 'finance' | 'admin' | 'super_admin'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'operations' | 'finance' | 'admin' | 'super_admin'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'operations' | 'finance' | 'admin' | 'super_admin'
          created_at?: string
          updated_at?: string
        }
      }
      currencies: {
        Row: {
          id: string
          code: string
          name: string
          symbol: string | null
          is_active: boolean
          is_default: boolean
          supported_countries: string[]
          created_at: string
          updated_at: string
        }
      }
      clients: {
        Row: {
          id: string
          name: string
          description: string | null
          logo_url: string | null
          created_at: string
          updated_at: string
          created_by: string | null
        }
      }
      projects: {
        Row: {
          id: string
          client_id: string
          name: string
          description: string | null
          status: 'draft' | 'active' | 'completed' | 'cancelled'
          start_date: string | null
          end_date: string | null
          budget: number | null
          budget_currency_id: string | null
          created_at: string
          updated_at: string
          created_by: string | null
        }
      }
      project_members: {
        Row: {
          id: string
          project_id: string
          user_id: string
          can_request_payment: boolean
          created_at: string
        }
      }
      influencers: {
        Row: {
          id: string
          email: string | null
          display_name: string
          phone: string | null
          avatar_url: string | null
          bio: string | null
          timezone: string
          status: 'pending' | 'active' | 'inactive'
          platform: string[] | null
          followers_count: number | null
          channel_urls: Record<string, string> | null
          location: string | null
          youtube_channel_id: string | null
          channel_handle: string | null
          channel_description: string | null
          channel_banner_url: string | null
          total_views: number | null
          video_count: number | null
          channel_created_at: string | null
          website: string | null
          twitter: string | null
          facebook: string | null
          linkedin: string | null
          instagram: string | null
          tiktok: string | null
          twitch: string | null
          created_at: string
          updated_at: string
          created_by: string | null
          registered_at: string | null
          last_collected_at: string | null
        }
      }
      videos: {
        Row: {
          id: string
          influencer_id: string
          video_id: string
          title: string
          description: string | null
          thumbnail_url: string | null
          duration: string | null
          view_count: string | null
          published_at: string | null
          video_url: string
          created_at: string
          updated_at: string
        }
      }
      collaborations: {
        Row: {
          id: string
          project_id: string
          influencer_id: string
          title: string
          description: string | null
          total_amount: number
          currency_id: string
          status: 'draft' | 'active' | 'completed' | 'cancelled'
          deliverables_confirmed: boolean
          deliverables_confirmed_by: string | null
          deliverables_confirmed_at: string | null
          created_at: string
          updated_at: string
          created_by: string | null
        }
      }
      deliverables: {
        Row: {
          id: string
          collaboration_id: string
          title: string
          description: string | null
          due_date: string | null
          status: 'pending' | 'completed' | 'approved'
          completed_at: string | null
          approved_by: string | null
          approved_at: string | null
          created_at: string
        }
      }
      companies: {
        Row: {
          id: string
          owner_id: string
          name: string
          email: string | null
          address: string | null
          tax_id: string | null
          country: string
          logo_url: string | null
          created_at: string
          updated_at: string
        }
      }
      invoices: {
        Row: {
          id: string
          collaboration_id: string | null
          company_id: string | null
          invoice_number: string | null
          amount: number
          currency_id: string
          source_type: 'uploaded' | 'generated'
          file_url: string | null
          invoice_date: string | null
          due_date: string | null
          notes: string | null
          status: 'draft' | 'submitted' | 'approved' | 'rejected'
          submitted_by: string | null
          submitted_at: string | null
          approved_by: string | null
          approved_at: string | null
          created_at: string
          updated_at: string
        }
      }
      invoice_items: {
        Row: {
          id: string
          invoice_id: string
          description: string
          quantity: number
          unit_price: number
          amount: number
          created_at: string
        }
      }
      payments: {
        Row: {
          id: string
          collaboration_id: string
          invoice_id: string | null
          requested_amount: number
          requested_currency_id: string
          requested_by: string
          requested_at: string
          status: 'pending' | 'paid' | 'rejected' | 'cancelled'
          paid_by: string | null
          paid_at: string | null
          actual_amount: number | null
          actual_currency_id: string | null
          exchange_rate: number | null
          payment_reference: string | null
          receipt_url: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
      }
      bank_accounts: {
        Row: {
          id: string
          influencer_id: string
          account_name: string
          bank_name: string | null
          country: string
          currency_id: string
          account_type: string | null
          account_number_encrypted: string | null
          routing_number_encrypted: string | null
          iban_encrypted: string | null
          swift_bic: string | null
          airwallex_contact_id: string | null
          airwallex_account_id: string | null
          airwallex_verification_status: string | null
          airwallex_verified_at: string | null
          is_verified: boolean
          is_default: boolean
          created_at: string
          updated_at: string
        }
      }
      posts: {
        Row: {
          id: string
          influencer_id: string
          platform: string
          platform_post_id: string
          url: string
          title: string | null
          description: string | null
          thumbnail_url: string | null
          published_at: string | null
          duration: string | null
          last_synced_at: string | null
          comments_disabled: boolean
          tags: string[]
          hashtags: string[]
          channel_title: string | null
          language: string | null
          category_id: number | null
          transcription: string | null
          transcription_source: string | null
          transcription_status: string | null
          transcription_language: string | null
          transcription_error: string | null
          transcription_quota_cost: number
          video_sentiment: Record<string, unknown> | null
          video_sentiment_status: string | null
          comment_sentiment: Record<string, unknown> | null
          comment_sentiment_status: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          influencer_id: string
          platform: string
          platform_post_id: string
          url: string
          title?: string | null
          description?: string | null
          thumbnail_url?: string | null
          published_at?: string | null
          duration?: string | null
          last_synced_at?: string | null
          comments_disabled?: boolean
          tags?: string[]
          hashtags?: string[]
          channel_title?: string | null
          language?: string | null
          category_id?: number | null
          transcription?: string | null
          transcription_source?: string | null
          transcription_status?: string | null
          transcription_language?: string | null
          transcription_error?: string | null
          transcription_quota_cost?: number
          video_sentiment?: Record<string, unknown> | null
          video_sentiment_status?: string | null
          comment_sentiment?: Record<string, unknown> | null
          comment_sentiment_status?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          influencer_id?: string
          platform?: string
          platform_post_id?: string
          url?: string
          title?: string | null
          description?: string | null
          thumbnail_url?: string | null
          published_at?: string | null
          duration?: string | null
          last_synced_at?: string | null
          comments_disabled?: boolean
          tags?: string[]
          hashtags?: string[]
          channel_title?: string | null
          language?: string | null
          category_id?: number | null
          transcription?: string | null
          transcription_source?: string | null
          transcription_status?: string | null
          transcription_language?: string | null
          transcription_error?: string | null
          transcription_quota_cost?: number
          video_sentiment?: Record<string, unknown> | null
          video_sentiment_status?: string | null
          comment_sentiment?: Record<string, unknown> | null
          comment_sentiment_status?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      post_snapshots: {
        Row: {
          id: string
          post_id: string
          view_count: number | null
          like_count: number | null
          comment_count: number | null
          share_count: number | null
          snapshot_at: string
        }
        Insert: {
          id?: string
          post_id: string
          view_count?: number | null
          like_count?: number | null
          comment_count?: number | null
          share_count?: number | null
          snapshot_at?: string
        }
        Update: {
          id?: string
          post_id?: string
          view_count?: number | null
          like_count?: number | null
          comment_count?: number | null
          share_count?: number | null
          snapshot_at?: string
        }
      }
      post_comments: {
        Row: {
          id: string
          post_id: string
          platform_comment_id: string
          author_name: string | null
          author_avatar_url: string | null
          author_channel_url: string | null
          text: string
          like_count: number
          published_at: string | null
          updated_at: string | null
          is_reply: boolean
          parent_comment_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          post_id: string
          platform_comment_id: string
          author_name?: string | null
          author_avatar_url?: string | null
          author_channel_url?: string | null
          text: string
          like_count?: number
          published_at?: string | null
          updated_at?: string | null
          is_reply?: boolean
          parent_comment_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          post_id?: string
          platform_comment_id?: string
          author_name?: string | null
          author_avatar_url?: string | null
          author_channel_url?: string | null
          text?: string
          like_count?: number
          published_at?: string | null
          updated_at?: string | null
          is_reply?: boolean
          parent_comment_id?: string | null
          created_at?: string
        }
      }
      transcription_usage: {
        Row: {
          id: string
          user_id: string
          year_month: string
          used_seconds: number
          quota_seconds: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          year_month: string
          used_seconds?: number
          quota_seconds?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          year_month?: string
          used_seconds?: number
          quota_seconds?: number
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}
