// Generated database types for Supabase
// This will be auto-generated by supabase gen types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: 'operations' | 'finance' | 'admin' | 'super_admin'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'operations' | 'finance' | 'admin' | 'super_admin'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'operations' | 'finance' | 'admin' | 'super_admin'
          created_at?: string
          updated_at?: string
        }
      }
      currencies: {
        Row: {
          id: string
          code: string
          name: string
          symbol: string | null
          is_active: boolean
          is_default: boolean
          supported_countries: string[]
          created_at: string
          updated_at: string
        }
      }
      clients: {
        Row: {
          id: string
          name: string
          description: string | null
          logo_url: string | null
          created_at: string
          updated_at: string
          created_by: string | null
        }
      }
      projects: {
        Row: {
          id: string
          client_id: string
          name: string
          description: string | null
          status: 'draft' | 'active' | 'completed' | 'cancelled'
          start_date: string | null
          end_date: string | null
          budget: number | null
          budget_currency_id: string | null
          created_at: string
          updated_at: string
          created_by: string | null
        }
      }
      project_members: {
        Row: {
          id: string
          project_id: string
          user_id: string
          can_request_payment: boolean
          created_at: string
        }
      }
      influencers: {
        Row: {
          id: string
          email: string | null
          display_name: string
          phone: string | null
          avatar_url: string | null
          bio: string | null
          timezone: string
          status: 'pending' | 'active' | 'inactive'
          created_at: string
          updated_at: string
          created_by: string | null
          registered_at: string | null
        }
      }
      collaborations: {
        Row: {
          id: string
          project_id: string
          influencer_id: string
          title: string
          description: string | null
          total_amount: number
          currency_id: string
          status: 'draft' | 'active' | 'completed' | 'cancelled'
          deliverables_confirmed: boolean
          deliverables_confirmed_by: string | null
          deliverables_confirmed_at: string | null
          created_at: string
          updated_at: string
          created_by: string | null
        }
      }
      deliverables: {
        Row: {
          id: string
          collaboration_id: string
          title: string
          description: string | null
          due_date: string | null
          status: 'pending' | 'completed' | 'approved'
          completed_at: string | null
          approved_by: string | null
          approved_at: string | null
          created_at: string
        }
      }
      companies: {
        Row: {
          id: string
          owner_id: string
          name: string
          email: string | null
          address: string | null
          tax_id: string | null
          country: string
          logo_url: string | null
          created_at: string
          updated_at: string
        }
      }
      invoices: {
        Row: {
          id: string
          collaboration_id: string | null
          company_id: string | null
          invoice_number: string | null
          amount: number
          currency_id: string
          source_type: 'uploaded' | 'generated'
          file_url: string | null
          invoice_date: string | null
          due_date: string | null
          notes: string | null
          status: 'draft' | 'submitted' | 'approved' | 'rejected'
          submitted_by: string | null
          submitted_at: string | null
          approved_by: string | null
          approved_at: string | null
          created_at: string
          updated_at: string
        }
      }
      invoice_items: {
        Row: {
          id: string
          invoice_id: string
          description: string
          quantity: number
          unit_price: number
          amount: number
          created_at: string
        }
      }
      payments: {
        Row: {
          id: string
          collaboration_id: string
          invoice_id: string | null
          requested_amount: number
          requested_currency_id: string
          requested_by: string
          requested_at: string
          status: 'pending' | 'paid' | 'rejected' | 'cancelled'
          paid_by: string | null
          paid_at: string | null
          actual_amount: number | null
          actual_currency_id: string | null
          exchange_rate: number | null
          payment_reference: string | null
          receipt_url: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
      }
      bank_accounts: {
        Row: {
          id: string
          influencer_id: string
          account_name: string
          bank_name: string | null
          country: string
          currency_id: string
          account_type: string | null
          account_number_encrypted: string | null
          routing_number_encrypted: string | null
          iban_encrypted: string | null
          swift_bic: string | null
          airwallex_contact_id: string | null
          airwallex_account_id: string | null
          airwallex_verification_status: string | null
          airwallex_verified_at: string | null
          is_verified: boolean
          is_default: boolean
          created_at: string
          updated_at: string
        }
      }
    }
  }
}
